# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gwncppvgb_swig', [dirname(__file__)])
        except ImportError:
            import _gwncppvgb_swig
            return _gwncppvgb_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_gwncppvgb_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _gwncppvgb_swig = swig_import_helper()
    del swig_import_helper
else:
    import _gwncppvgb_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
    """high_res_timer_now() -> gr::high_res_timer_type"""
    return _gwncppvgb_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
    """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
    return _gwncppvgb_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
    """high_res_timer_tps() -> gr::high_res_timer_type"""
    return _gwncppvgb_swig.high_res_timer_tps()

def high_res_timer_epoch():
    """high_res_timer_epoch() -> gr::high_res_timer_type"""
    return _gwncppvgb_swig.high_res_timer_epoch()
class gwnblock(object):
    """
    <+description of block+>

    Constructor Specific Documentation:

    Return a shared_ptr to a new instance of gwncppvgb::gwnblock.

    To avoid accidental use of raw pointers, gwncppvgb::gwnblock's constructor is in a private implementation class. gwncppvgb::gwnblock::make is the public interface for creating new instances.

    Args:
        name : 
        number_in : 
        number_out : 
        number_timers : 
        number_timeouts : 
    """

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def make(*args, **kwargs):
        """
        make(std::string name, int number_in=0, int number_out=0, int number_timers=0, int number_timeouts=0) -> gwnblock_sptr

        <+description of block+>

        Constructor Specific Documentation:

        Return a shared_ptr to a new instance of gwncppvgb::gwnblock.

        To avoid accidental use of raw pointers, gwncppvgb::gwnblock's constructor is in a private implementation class. gwncppvgb::gwnblock::make is the public interface for creating new instances.

        Args:
            name : 
            number_in : 
            number_out : 
            number_timers : 
            number_timeouts : 
        """
        return _gwncppvgb_swig.gwnblock_make(*args, **kwargs)

    make = staticmethod(make)
    __swig_destroy__ = _gwncppvgb_swig.delete_gwnblock
    __del__ = lambda self: None
gwnblock_swigregister = _gwncppvgb_swig.gwnblock_swigregister
gwnblock_swigregister(gwnblock)

def gwnblock_make(*args, **kwargs):
    """
    gwnblock_make(std::string name, int number_in=0, int number_out=0, int number_timers=0, int number_timeouts=0) -> gwnblock_sptr

    <+description of block+>

    Constructor Specific Documentation:

    Return a shared_ptr to a new instance of gwncppvgb::gwnblock.

    To avoid accidental use of raw pointers, gwncppvgb::gwnblock's constructor is in a private implementation class. gwncppvgb::gwnblock::make is the public interface for creating new instances.

    Args:
        name : 
        number_in : 
        number_out : 
        number_timers : 
        number_timeouts : 
    """
    return _gwncppvgb_swig.gwnblock_make(*args, **kwargs)

class gwnblock_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::gwncppvgb::gwnblock)> class."""

    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        __init__(boost::shared_ptr<(gr::gwncppvgb::gwnblock)> self) -> gwnblock_sptr
        __init__(boost::shared_ptr<(gr::gwncppvgb::gwnblock)> self, gwnblock p) -> gwnblock_sptr
        """
        this = _gwncppvgb_swig.new_gwnblock_sptr(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def __deref__(self):
        """__deref__(gwnblock_sptr self) -> gwnblock"""
        return _gwncppvgb_swig.gwnblock_sptr___deref__(self)

    __swig_destroy__ = _gwncppvgb_swig.delete_gwnblock_sptr
    __del__ = lambda self: None

    def make(self, *args, **kwargs):
        """
        make(gwnblock_sptr self, std::string name, int number_in=0, int number_out=0, int number_timers=0, int number_timeouts=0) -> gwnblock_sptr

        <+description of block+>

        Constructor Specific Documentation:

        Return a shared_ptr to a new instance of gwncppvgb::gwnblock.

        To avoid accidental use of raw pointers, gwncppvgb::gwnblock's constructor is in a private implementation class. gwncppvgb::gwnblock::make is the public interface for creating new instances.

        Args:
            name : 
            number_in : 
            number_out : 
            number_timers : 
            number_timeouts : 
        """
        return _gwncppvgb_swig.gwnblock_sptr_make(self, *args, **kwargs)


    def history(self):
        """history(gwnblock_sptr self) -> unsigned int"""
        return _gwncppvgb_swig.gwnblock_sptr_history(self)


    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(gwnblock_sptr self, int which, int delay)
        declare_sample_delay(gwnblock_sptr self, unsigned int delay)
        """
        return _gwncppvgb_swig.gwnblock_sptr_declare_sample_delay(self, *args)


    def sample_delay(self, which):
        """sample_delay(gwnblock_sptr self, int which) -> unsigned int"""
        return _gwncppvgb_swig.gwnblock_sptr_sample_delay(self, which)


    def output_multiple(self):
        """output_multiple(gwnblock_sptr self) -> int"""
        return _gwncppvgb_swig.gwnblock_sptr_output_multiple(self)


    def relative_rate(self):
        """relative_rate(gwnblock_sptr self) -> double"""
        return _gwncppvgb_swig.gwnblock_sptr_relative_rate(self)


    def start(self):
        """start(gwnblock_sptr self) -> bool"""
        return _gwncppvgb_swig.gwnblock_sptr_start(self)


    def stop(self):
        """stop(gwnblock_sptr self) -> bool"""
        return _gwncppvgb_swig.gwnblock_sptr_stop(self)


    def nitems_read(self, which_input):
        """nitems_read(gwnblock_sptr self, unsigned int which_input) -> uint64_t"""
        return _gwncppvgb_swig.gwnblock_sptr_nitems_read(self, which_input)


    def nitems_written(self, which_output):
        """nitems_written(gwnblock_sptr self, unsigned int which_output) -> uint64_t"""
        return _gwncppvgb_swig.gwnblock_sptr_nitems_written(self, which_output)


    def max_noutput_items(self):
        """max_noutput_items(gwnblock_sptr self) -> int"""
        return _gwncppvgb_swig.gwnblock_sptr_max_noutput_items(self)


    def set_max_noutput_items(self, m):
        """set_max_noutput_items(gwnblock_sptr self, int m)"""
        return _gwncppvgb_swig.gwnblock_sptr_set_max_noutput_items(self, m)


    def unset_max_noutput_items(self):
        """unset_max_noutput_items(gwnblock_sptr self)"""
        return _gwncppvgb_swig.gwnblock_sptr_unset_max_noutput_items(self)


    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(gwnblock_sptr self) -> bool"""
        return _gwncppvgb_swig.gwnblock_sptr_is_set_max_noutput_items(self)


    def set_min_noutput_items(self, m):
        """set_min_noutput_items(gwnblock_sptr self, int m)"""
        return _gwncppvgb_swig.gwnblock_sptr_set_min_noutput_items(self, m)


    def min_noutput_items(self):
        """min_noutput_items(gwnblock_sptr self) -> int"""
        return _gwncppvgb_swig.gwnblock_sptr_min_noutput_items(self)


    def max_output_buffer(self, i):
        """max_output_buffer(gwnblock_sptr self, int i) -> long"""
        return _gwncppvgb_swig.gwnblock_sptr_max_output_buffer(self, i)


    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(gwnblock_sptr self, long max_output_buffer)
        set_max_output_buffer(gwnblock_sptr self, int port, long max_output_buffer)
        """
        return _gwncppvgb_swig.gwnblock_sptr_set_max_output_buffer(self, *args)


    def min_output_buffer(self, i):
        """min_output_buffer(gwnblock_sptr self, int i) -> long"""
        return _gwncppvgb_swig.gwnblock_sptr_min_output_buffer(self, i)


    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(gwnblock_sptr self, long min_output_buffer)
        set_min_output_buffer(gwnblock_sptr self, int port, long min_output_buffer)
        """
        return _gwncppvgb_swig.gwnblock_sptr_set_min_output_buffer(self, *args)


    def pc_noutput_items(self):
        """pc_noutput_items(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_noutput_items(self)


    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_noutput_items_avg(self)


    def pc_noutput_items_var(self):
        """pc_noutput_items_var(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_noutput_items_var(self)


    def pc_nproduced(self):
        """pc_nproduced(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_nproduced(self)


    def pc_nproduced_avg(self):
        """pc_nproduced_avg(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_nproduced_avg(self)


    def pc_nproduced_var(self):
        """pc_nproduced_var(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_nproduced_var(self)


    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(gwnblock_sptr self, int which) -> float
        pc_input_buffers_full(gwnblock_sptr self) -> pmt_vector_float
        """
        return _gwncppvgb_swig.gwnblock_sptr_pc_input_buffers_full(self, *args)


    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(gwnblock_sptr self, int which) -> float
        pc_input_buffers_full_avg(gwnblock_sptr self) -> pmt_vector_float
        """
        return _gwncppvgb_swig.gwnblock_sptr_pc_input_buffers_full_avg(self, *args)


    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(gwnblock_sptr self, int which) -> float
        pc_input_buffers_full_var(gwnblock_sptr self) -> pmt_vector_float
        """
        return _gwncppvgb_swig.gwnblock_sptr_pc_input_buffers_full_var(self, *args)


    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(gwnblock_sptr self, int which) -> float
        pc_output_buffers_full(gwnblock_sptr self) -> pmt_vector_float
        """
        return _gwncppvgb_swig.gwnblock_sptr_pc_output_buffers_full(self, *args)


    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(gwnblock_sptr self, int which) -> float
        pc_output_buffers_full_avg(gwnblock_sptr self) -> pmt_vector_float
        """
        return _gwncppvgb_swig.gwnblock_sptr_pc_output_buffers_full_avg(self, *args)


    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(gwnblock_sptr self, int which) -> float
        pc_output_buffers_full_var(gwnblock_sptr self) -> pmt_vector_float
        """
        return _gwncppvgb_swig.gwnblock_sptr_pc_output_buffers_full_var(self, *args)


    def pc_work_time(self):
        """pc_work_time(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_work_time(self)


    def pc_work_time_avg(self):
        """pc_work_time_avg(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_work_time_avg(self)


    def pc_work_time_var(self):
        """pc_work_time_var(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_work_time_var(self)


    def pc_work_time_total(self):
        """pc_work_time_total(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_work_time_total(self)


    def pc_throughput_avg(self):
        """pc_throughput_avg(gwnblock_sptr self) -> float"""
        return _gwncppvgb_swig.gwnblock_sptr_pc_throughput_avg(self)


    def set_processor_affinity(self, mask):
        """set_processor_affinity(gwnblock_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _gwncppvgb_swig.gwnblock_sptr_set_processor_affinity(self, mask)


    def unset_processor_affinity(self):
        """unset_processor_affinity(gwnblock_sptr self)"""
        return _gwncppvgb_swig.gwnblock_sptr_unset_processor_affinity(self)


    def processor_affinity(self):
        """processor_affinity(gwnblock_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _gwncppvgb_swig.gwnblock_sptr_processor_affinity(self)


    def active_thread_priority(self):
        """active_thread_priority(gwnblock_sptr self) -> int"""
        return _gwncppvgb_swig.gwnblock_sptr_active_thread_priority(self)


    def thread_priority(self):
        """thread_priority(gwnblock_sptr self) -> int"""
        return _gwncppvgb_swig.gwnblock_sptr_thread_priority(self)


    def set_thread_priority(self, priority):
        """set_thread_priority(gwnblock_sptr self, int priority) -> int"""
        return _gwncppvgb_swig.gwnblock_sptr_set_thread_priority(self, priority)


    def name(self):
        """name(gwnblock_sptr self) -> std::string"""
        return _gwncppvgb_swig.gwnblock_sptr_name(self)


    def symbol_name(self):
        """symbol_name(gwnblock_sptr self) -> std::string"""
        return _gwncppvgb_swig.gwnblock_sptr_symbol_name(self)


    def input_signature(self):
        """input_signature(gwnblock_sptr self) -> io_signature_sptr"""
        return _gwncppvgb_swig.gwnblock_sptr_input_signature(self)


    def output_signature(self):
        """output_signature(gwnblock_sptr self) -> io_signature_sptr"""
        return _gwncppvgb_swig.gwnblock_sptr_output_signature(self)


    def unique_id(self):
        """unique_id(gwnblock_sptr self) -> long"""
        return _gwncppvgb_swig.gwnblock_sptr_unique_id(self)


    def to_basic_block(self):
        """to_basic_block(gwnblock_sptr self) -> basic_block_sptr"""
        return _gwncppvgb_swig.gwnblock_sptr_to_basic_block(self)


    def check_topology(self, ninputs, noutputs):
        """check_topology(gwnblock_sptr self, int ninputs, int noutputs) -> bool"""
        return _gwncppvgb_swig.gwnblock_sptr_check_topology(self, ninputs, noutputs)


    def alias(self):
        """alias(gwnblock_sptr self) -> std::string"""
        return _gwncppvgb_swig.gwnblock_sptr_alias(self)


    def set_block_alias(self, name):
        """set_block_alias(gwnblock_sptr self, std::string name)"""
        return _gwncppvgb_swig.gwnblock_sptr_set_block_alias(self, name)


    def _post(self, which_port, msg):
        """_post(gwnblock_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _gwncppvgb_swig.gwnblock_sptr__post(self, which_port, msg)


    def message_ports_in(self):
        """message_ports_in(gwnblock_sptr self) -> swig_int_ptr"""
        return _gwncppvgb_swig.gwnblock_sptr_message_ports_in(self)


    def message_ports_out(self):
        """message_ports_out(gwnblock_sptr self) -> swig_int_ptr"""
        return _gwncppvgb_swig.gwnblock_sptr_message_ports_out(self)


    def message_subscribers(self, which_port):
        """message_subscribers(gwnblock_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _gwncppvgb_swig.gwnblock_sptr_message_subscribers(self, which_port)

gwnblock_sptr_swigregister = _gwncppvgb_swig.gwnblock_sptr_swigregister
gwnblock_sptr_swigregister(gwnblock_sptr)


gwnblock_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
gwnblock = gwnblock.make;



